#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Bump version in DESCRIPTION file
PKG_VERSION=`grep -i ^version DESCRIPTION | sed -E 's/^Version:[[:space:]]+//'`
PKG_NEXT_VERSION=`echo $PKG_VERSION | sed -E 's/(.+)([[:digit:]]+$$)/\2/'`
PKG_PREFIX_VERSION=`echo $PKG_VERSION | sed -E 's/(.+)([[:digit:]]+$$)/\1/'`
PKG_VERSION=$PKG_PREFIX_VERSION$((PKG_NEXT_VERSION+1))
sed -E 's/^Version:[[:space:]]+.*/Version: '"$PKG_VERSION"'/' < DESCRIPTION > DESCRIPTION_tmp
mv DESCRIPTION_tmp DESCRIPTION
git add DESCRIPTION
